### ISSUE TITLE
Weekly rewards: add liquidity

### ISSUE THREAD

**Issue by adamazad** [SwaprHQ/swapr-expeditions-services#7]
**Weekly**
Users should be prompted to provide new liquidity, worth at least 50 USD to claim during 5 different weeks. Eligible for 50 fragments, with an additional 50 fragments for each week completed, for a max of 750 throughout the 5-week campaign. Missing a week does not reset the user back to 50, but instead doesn’t increase their next claim.

- ~~Each $1 = 1 fragment.~~
- Maximum fragments = 750.
- Week starts on Monday at 00:00 AM UTC.
- Week ends on Sunday at 11:59 PM UTC.
- Past completed week adds 50 fragments to the total fragments.

**Comment by KeenanLukeOM** [comment]
This is correct, except the `Each $1 = 1 fragment.` line. 

$ value should be ignored in the calculation of fragments provided there is sufficient $ for eligibility (In this case, at least $50 of liq). $1 only = 1 fragment with exactly $50 of liquidity, if the user deposits $1m they are still only eligible for 50 fragments.
