### ISSUE TITLE
Weekly rewards: staking

### ISSUE THREAD

**Issue by adamazad** [SwaprHQ/swapr-expeditions-services#8]
**Weekly**

Stake their LP in a reward campaign, users should have staked at least $50 of LP tokens in a DIY farming campaign (maybe one of DXdao deployed campaigns only?). Eligible for 50 fragments, with an additional 50 fragments for each week completed, for a max of 750 throughout the 5-week campaign. Missing a week does not reset the user back to 50, but instead doesn’t increase their next claim.

- ~~Each $1 = 1 fragment.~~
- Maximum fragments = 750.
- Week starts on Monday at 00:00 AM UTC.
- Week ends on Sunday at 11:59 PM UTC.
- Past completed week adds 50 fragments to the total fragments.

Currently proposed query:
```typescript
import { gql } from '@apollo/client';

export const GetLiquidityMiningCampaignDepositsQuery = gql`
  query GetLiquidityMiningCampaignDeposits($user: Bytes!, $timestampStart: BigInt!, $timestampEnd: BigInt!) {
    liquidityMiningCampaignDeposits: deposits(
      where: { user: $user, timestamp_gte: $timestampStart, timestamp_lte: $timestampEnd }
    ) {
      id
      amount
      timestamp
      liquidityMiningCampaign {
        id
        stakablePair {
          id
          reserveUSD
          token0 {
            id
            symbol
          }
          token1 {
            id
            symbol
          }
        }
      }
    }
    singleSidedStakingCampaignDeposits(
      where: { user: $user, timestamp_gte: $timestampStart, timestamp_lte: $timestampEnd }
    ) {
      id
      amount
      timestamp
      singleSidedStakingCampaign {
        stakeToken {
          id
          symbol
        }
      }
    }
  }
`;
```

**Comment by KeenanLukeOM** [comment]
Same comments as issue #7
